version: '3.7'
services:
  database:
    container_name: postgres_financial_app_dev
    image: postgres:11.5
    environment:
      POSTGRES_DB: financial_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"